/**
 * The version this package reports when it registers with the server.
 *
 * GENERATED by scripts/sync-version.mjs from package.json. Do not edit: the
 * next build overwrites it, and a test fails if the two disagree.
 */
export const SDK_VERSION = "0.2.2";
