/**
 * Writes src/version.ts from the version in package.json.
 *
 * The version has to reach the server as a string in the bundle, and the only
 * place it can honestly come from is the manifest that npm publishes. Written
 * out rather than imported: importing package.json from src drags the manifest
 * into the build output and out of rootDir, and pins the consumer to a
 * resolveJsonModule setting they never asked for.
 *
 * Runs before every build. A test in each package compares the two, so a file
 * edited by hand fails the suite instead of shipping a version nobody used.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const packageDir = process.cwd();
const { name, version } = JSON.parse(
  readFileSync(join(packageDir, "package.json"), "utf8"),
);

const target = join(packageDir, "src", "version.ts");
const contents = `/**
 * The version this package reports when it registers with the server.
 *
 * GENERATED by scripts/sync-version.mjs from package.json. Do not edit: the
 * next build overwrites it, and a test fails if the two disagree.
 */
export const SDK_VERSION = ${JSON.stringify(version)};
`;

let previous = "";
try {
  previous = readFileSync(target, "utf8");
} catch {
  // First run for this package.
}

if (previous === contents) {
  console.log(`${name}: version.ts already at ${version}`);
} else {
  writeFileSync(target, contents);
  console.log(`${name}: version.ts written at ${version}`);
}
